version: '3.5'
services:
  db:
    image: 'postgres:14.2-alpine'
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=educationalwebsite
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  educational_website:
    container_name: educational_website
    restart: on-failure
    build: ./
    ports:
      - "9000:9000"
    depends_on:
      - db
      - liquibase
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/educationalwebsite
      - SPRING_DATASOURCE_USERNAME=postgres

  liquibase:
    image: 'liquibase/liquibase'
    container_name: liquibase
    depends_on:
      - db
    hostname: liquibase
    environment:
      POSTGRES_DB: educationalwebsite
      POSTGRES_USER: postgres
