version: '3.5'
services:
  db:
    image: 'postgres:14.2'
    restart: always
    container_name: db
    build:
      context: ..
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=websitedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1988
      - POSTGRES_HOST_AUTH_METHOD=trust

  educational_website:
    container_name: educational_website
    restart: on-failure
    image: educational_website
    build:
      context: ..
    ports:
      - "9000:9000"
    depends_on:
      - db
      - liquibase
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/websitedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1988


  liquibase:
    image: 'liquibase/liquibase'
    container_name: liquibase
    depends_on:
      - db
    hostname: liquibase
    environment:
      POSTGRES_DB: websitedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1988
